// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Intl_NumberFormat from "bs-intl/src/Intl_NumberFormat.bs.js";

var formatter = Intl_NumberFormat.make(/* array */["da-DK"], undefined, /* Currency */[/* record */[
        /* isoCode */"DKK",
        /* display */undefined
      ]], undefined, undefined, /* () */0);

function formatPrice(price) {
  return Intl_NumberFormat.format(formatter, price / 100);
}

function capitalize(str) {
  return str.charAt(0) + str.slice(1);
}

export {
  formatter ,
  formatPrice ,
  capitalize ,
  
}
/* formatter Not a pure module */
