// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var formatPrice = (
function(price) {
  const formatter = new Intl.NumberFormat('da-DK', {
    style: 'currency',
    currency: 'DKK',
  })
  return formatter.format(price / 100)
});

function capitalize(str) {
  return str.charAt(0) + str.slice(1);
}

export {
  formatPrice ,
  capitalize ,
  
}
/* formatPrice Not a pure module */
